export const LOAD_SONGS_REQUEST = 'LOAD_SONGS_REQUEST';
export const LOAD_SONGS_SUCCESS = 'LOAD_SONGS_SUCCESS';
export const LOAD_SONGS_FAILURE = 'LOAD_SONGS_FAILURE';

export const SET_VIEWPORT = 'SET_VIEWPORT';

export const SELECT_SONG = 'SELECT_SONG';

export const PREV_SONG = 'PREV_SONG';
export const NEXT_SONG = 'NEXT_SONG';




