export const LOAD_SONGS_REQUEST = 'LOAD_SONGS_REQUEST';
export const LOAD_SONGS_SUCCESS = 'LOAD_SONGS_SUCCESS';
// export const LOAD_SONGS_FAILURE = 'LOAD_SONGS_FAILURE';
//
// export const UPDATE_SINGLE_MACHINE_REQUEST = 'UPDATE_SINGLE_MACHINE_REQUEST';
// export const UPDATE_SINGLE_MACHINE_SUCCESS = 'UPDATE_SINGLE_MACHINE_SUCCESS';
// export const UPDATE_SINGLE_MACHINE_FAILURE = 'UPDATE_SINGLE_MACHINE_FAILURE';
//
// export const SUGGEST_MACHINES_REQUEST = 'SUGGEST_MACHINES_REQUEST';
// export const SUGGEST_MACHINES_SUCCESS = 'SUGGEST_MACHINES_SUCCESS';
// export const SUGGEST_MACHINES_FAILURE = 'SUGGEST_MACHINES_FAILURE';
//
// export const CLEAR_MACHINES_SUGGESTER_CACHE = 'CLEAR_MACHINES_SUGGESTER_CACHE';
//
// export const LOAD_MACHINE_OPERATION_STATUSES_REQUEST = 'LOAD_MACHINE_OPERATION_STATUSES_REQUEST';
// export const LOAD_MACHINE_OPERATION_STATUSES_SUCCESS = 'LOAD_MACHINE_OPERATION_STATUSES_SUCCESS';
// export const LOAD_MACHINE_OPERATION_STATUSES_FAILURE = 'LOAD_MACHINE_OPERATION_STATUSES_FAILURE';
//
// export const LAUNCH_OPERATION_REQUEST = 'LAUNCH_OPERATION_REQUEST';
// export const LAUNCH_OPERATION_SUCCESS = 'LAUNCH_OPERATION_SUCCESS';
// export const LAUNCH_OPERATION_FAILURE = 'LAUNCH_OPERATION_FAILURE';
//
// export const UNBIND_OPERATION_FROM_TAG_REQUEST = 'UNBIND_OPERATION_FROM_TAG_REQUEST';
// export const UNBIND_OPERATION_FROM_TAG_SUCCESS = 'UNBIND_OPERATION_FROM_TAG_SUCCESS';
// export const UNBIND_OPERATION_FROM_TAG_FAILURE = 'UNBIND_OPERATION_FROM_TAG_FAILURE';
//
// export const CANCEL_OPERATION_REQUEST = 'CANCEL_OPERATION_REQUEST';
// export const CANCEL_OPERATION_SUCCESS = 'CANCEL_OPERATION_SUCCESS';
// export const CANCEL_OPERATION_FAILURE = 'CANCEL_OPERATION_FAILURE';
//
// export const CANCEL_OPERATION_STATUS_REQUEST = 'CANCEL_OPERATION_STATUS_REQUEST';
// export const CANCEL_OPERATION_STATUS_SUCCESS = 'CANCEL_OPERATION_STATUS_SUCCESS';
// export const CANCEL_OPERATION_STATUS_FAILURE = 'CANCEL_OPERATION_STATUS_FAILURE';
//
// export const LOAD_OPERATION_STATUSES_BY_OPERATION_REQUEST = 'LOAD_OPERATION_STATUSES_BY_OPERATION_REQUEST';
// export const LOAD_OPERATION_STATUSES_BY_OPERATION_SUCCESS = 'LOAD_OPERATION_STATUSES_BY_OPERATION_SUCCESS';
// export const LOAD_OPERATION_STATUSES_BY_OPERATION_FAILURE = 'LOAD_OPERATION_STATUSES_BY_OPERATION_FAILURE';
//
// export const LOAD_OPERATIONS_REQUEST = 'LOAD_OPERATIONS_REQUEST';
// export const LOAD_OPERATIONS_SUCCESS = 'LOAD_OPERATIONS_SUCCESS';
// export const LOAD_OPERATIONS_FAILURE = 'LOAD_OPERATIONS_FAILURE';
// export const LOAD_OPERATION_TYPES_REQUEST = 'LOAD_OPERATION_TYPES_REQUEST';
// export const LOAD_OPERATION_TYPES_SUCCESS = 'LOAD_OPERATION_TYPES_SUCCESS';
// export const LOAD_OPERATION_TYPES_FAILURE = 'LOAD_OPERATION_TYPES_FAILURE';
//
// export const LOAD_TAGS_REQUEST = 'LOAD_TAGS_REQUEST';
// export const LOAD_TAGS_SUCCESS = 'LOAD_TAGS_SUCCESS';
// export const LOAD_TAGS_FAILURE = 'LOAD_TAGS_FAILURE';
//
// export const CREATE_TAG_REQUEST = 'CREATE_TAG_REQUEST';
// export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';
// export const CREATE_TAG_FAILURE = 'CREATE_TAG_FAILURE';
//
// export const UPDATE_TAG_DESCRIPTION_REQUEST = 'UPDATE_TAG_DESCRIPTION_REQUEST';
// export const UPDATE_TAG_DESCRIPTION_SUCCESS = 'UPDATE_TAG_DESCRIPTION_SUCCESS';
// export const UPDATE_TAG_DESCRIPTION_FAILURE = 'UPDATE_TAG_DESCRIPTION_FAILURE';
//
// export const UPDATE_TAG_MACHINES_REQUEST = 'UPDATE_TAG_MACHINES_REQUEST';
// export const UPDATE_TAG_MACHINES_SUCCESS = 'UPDATE_TAG_MACHINES_SUCCESS';
// export const UPDATE_TAG_MACHINES_FAILURE = 'UPDATE_TAG_MACHINES_FAILURE';
//
// export const WEBSOCKET_ASYNC_REQUEST = 'WEBSOCKET_ASYNC_REQUEST';
//
// export const SCREEN_SIZE_CHANGED = 'SCREEN_SIZE_CHANGED';

export const SET_VIEWPORT = 'SET_VIEWPORT';
// export const SHOW_MACHINE = 'SHOW_MACHINE';
// export const SHOW_ALL_MACHINES = 'SHOW_ALL_MACHINES';
// export const SHOW_ALL_TAGS = 'SHOW_ALL_TAGS';
// export const SHOW_TAG = 'SHOW_TAG';
// export const SHOW_OPERATION = 'SHOW_OPERATION';
// export const SHOW_ALL_OPERATIONS = 'SHOW_ALL_OPERATIONS';
//
// export const LOAD_RESOURCES_REQUEST = 'LOAD_RESOURCES_REQUEST';
// export const LOAD_RESOURCES_SUCCESS = 'LOAD_RESOURCES_SUCCESS';
// export const LOAD_RESOURCES_FAILURE = 'LOAD_RESOURCES_FAILURE';
//
// export const LOAD_LOG_LINES_BY_OPERATION_STATUS_REQUEST = 'LOAD_LOG_LINES_BY_OPERATION_STATUS_REQUEST';
// export const LOAD_LOG_LINES_BY_OPERATION_STATUS_SUCCESS = 'LOAD_LOG_LINES_BY_OPERATION_STATUS_SUCCESS';
// export const LOAD_LOG_LINES_BY_OPERATION_STATUS_FAILURE = 'LOAD_LOG_LINES_BY_OPERATION_STATUS_FAILURE';
//
// export const LOAD_LOG_LINES_BY_MACHINE_REQUEST = 'LOAD_LOG_LINES_BY_MACHINE_REQUEST';
// export const LOAD_LOG_LINES_BY_MACHINE_SUCCESS = 'LOAD_LOG_LINES_BY_MACHINE_SUCCESS';
// export const LOAD_LOG_LINES_BY_MACHINE_FAILURE = 'LOAD_LOG_LINES_BY_MACHINE_FAILURE';
